name: latentsdf
channels:
  - pytorch
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.6.24=0

  - cpuonly=1.0=0
 
  - freetype

  - icu
 
  - intel-openmp

  - jpeg

  - libpng
  - libtiff
  - lz4-c

  - matplotlib
  - matplotlib-base







  - openssl

  - pip=20.2.2=py37_0

  - pyqt
  - python=3.7.7
  - python-dateutil=2.8.1=py_0
  - pytorch=1.6.0=py3.7_cpu_0


  - qt

 
  - seaborn

  - sip
  - six=1.15.0=py_0
  - sqlite
  - tk
  - toolz=0.10.0=py_0

  - werkzeug=1.0.1=py_0
  - wheel=0.35.1=py_0

  - xz
  - zlib
  - zstd
  - pip:
    - altgraph==0.17
    - certifi==2020.6.20
    - click==7.1.2
    - cloudpickle==1.5.0
    - cycler==0.10.0
    - cytoolz==0.10.1
    - dask
    - decorator==4.4.2
    - flask==1.1.2
    - future==0.18.2
    - gunicorn
    - icc_rt
    - imageio==2.9.0
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - kiwisolver
    - markupsafe==1.1.1
    - mkl
    - mkl-service
    - mkl_fft
    - mkl_random
    - networkx==2.4
    - ninja==1.10.0
    - numpy==1.19.1
    - olefile==0.46
    - pandas==1.1.0
    - pefile==2019.4.18
    - Pillow==7.2.0
    - PyMCubes==0.1.0
    - pyparsing==2.4.7
    - pytz==2020.1
    - pywin32-ctypes==0.2.0
    - PyWavelets==1.1.1
    - scikit-image==0.16.2
    - scipy==1.5.2
    - setuptools==49.6.0
    - torchvision==0.7.0
    - tornado==6.0.4
    - wincertstore==0.2
    - vc
 